[profile.default]
solc_version="0.8.26"
evm_version = "paris"
src = "contracts"
out = "out"
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'
test = 'test'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = true
runs = 1000
ffi = true